# This is a complete configuration to deploy Loki backed by a s3-compatible API
# like MinIO for storage.
# Index files will be written locally at /loki/index and, eventually, will be shipped to the storage via tsdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: fineAnts_loki
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: aws
      schema: v13
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h
ingester:
  chunk_encoding: snappy
  chunk_idle_period: 2h        # 청크가 2시간 동안 비활성 상태일 경우 플러시
  chunk_target_size: 1536000   # 각 청크의 목표 크기
  max_chunk_age: 2h            # 청크 생명 시간

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    s3forcepathstyle: true
    s3: s3://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@ap-northeast-2/fineants2024
limits_config:
  max_line_size: 0
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 30
  per_stream_rate_limit: "3MB"
  per_stream_rate_limit_burst: "10MB"
compactor:
  working_directory: /loki/compactor

