spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.production.datasource.url}
    username: ${db.production.datasource.username}
    password: ${db.production.datasource.password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    co: info
server:
  port: 443
cron:
  expression:
    reload-stocks: '0 0 8 * * ?'
    closing-price: '0 0 16 * * ?'
    update-holidays: '0 0 0 * * ?'
