spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.local.datasource.url}
    username: ${db.local.datasource.username}
    password: ${db.local.datasource.password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath*:db/mysql/data.sql
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
logging:
  level:
    codesquad: debug
cron:
  expression:
    reload-stocks: '0 0 8 * * ?'
