spring:
  profiles:
    group:
      local: local, secret
      release: release, secret
      production: production, secret
      test: test, secret
    default: local
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
  cache:
    type: redis
  config:
    import:
      - ./secret/application-secret.yml
      - ./secret/application-oauth.yml
      - ./secret/application-prometheus.yml
      - ./member.yml
      - ./mail.yml
      - ./sse.yml
  application:
    name: fineAnts
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/
    mode: HTML5
    encoding: UTF-8
    check-template-location: true
  flyway:
    locations: classpath:db/mysql/migration
portfolio:
  securities-firm: BNK투자증권,부국증권,케이프투자증권,대신증권,다올투자증권,DB금융투자,이베스트투자증권,유진투자증권,하나증권,한화투자증권,하이투자증권
    ,현대차증권,IBK투자증권,카카오페이증권,KB증권,키움증권,한국투자증권,한국포스증권,교보증권,메리츠증권,미래에셋증권,나무증권,삼성증권,상상인증권,신한투자증권
    ,신영증권,SK증권,토스증권,유안타증권,FineAnts
cloud:
  aws:
    credentials:
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${aws.s3.bucket}
      dividend-bucket: ${aws.s3.dividend-bucket}
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
