spring:
  datasource:
    hikari:
      leak-detection-threshold: 2000
      connection-timeout: 30000
      max-lifetime: 30000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
logging:
  level:
    co: debug
scheduling:
  enabled: false
kis:
  websocket:
    auto-connect: false
