server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://logs-prod-030.grafana.net/loki/api/v1/push
    basic_auth:
      username: "${LOKI_USERNAME}"
      password: "${LOKI_PASSWORD}"
scrape_configs:
  - job_name: logs  # 통합된 job 이름
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          log_level: info  # info 레벨 라벨 추가
          __path__: /var/log/info/*.log
      - targets:
          - localhost
        labels:
          job: logs
          log_level: warn  # warn 레벨 라벨 추가
          __path__: /var/log/warn/*.log
      - targets:
          - localhost
        labels:
          job: logs
          log_level: error  # error 레벨 라벨 추가
          __path__: /var/log/error/*.log
    pipeline_stages:
      - regex:
          expression: '\\[traceId=(?P<traceId>[^\\]]+)\\]'
      - regex:
          expression: '.*HTTPMethod=(?P<HTTPMethod>[A-Z]+).*'
      - regex:
          expression: '.*Path=(?P<Path>https?://\S+).*'
      - regex:
          expression: '.*IP=(?P<IP>[0-9a-fA-F:]+).*'
      - labels:
          traceId: traceId
          HTTPMethod: HTTPMethod
          Path: Path
          IP: IP
